"""RLAIF (Reinforcement Learning from AI Feedback) and Explicit Feedback system.

This module provides:
1. RLAIF scoring - Uses DeepSeek Chat API to automatically score reports
2. Database storage for feedback (rl_feedback, user_feedback, prompt_versions)
3. Short-term learning mechanisms based on feedback patterns

PostgreSQL tables:
  - rl_feedback: AI-generated scores for each report dimension
  - user_feedback: Explicit user ratings and comments from UI
  - prompt_versions: Tracking prompt changes for A/B testing
"""

from __future__ import annotations

import json
import logging
import os
from typing import Any, Dict, List, Optional

import psycopg2
from psycopg2.extras import RealDictCursor

logger = logging.getLogger(__name__)

_DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY", "")
_DEEPSEEK_BASE_URL = os.getenv("DEEPSEEK_BASE_URL", "https://api.deepseek.com")
_DEEPSEEK_MODEL = os.getenv("DEEPSEEK_MODEL", "deepseek-chat")


def _get_pg_conn():
    """Open a new psycopg2 connection using env vars."""
    return psycopg2.connect(
        host=os.getenv("POSTGRES_HOST", "localhost"),
        port=int(os.getenv("POSTGRES_PORT", "5432")),
        dbname=os.getenv("POSTGRES_DB", "airflow"),
        user=os.getenv("POSTGRES_USER", "airflow"),
        password=os.getenv("POSTGRES_PASSWORD", "airflow"),
    )


def ensure_feedback_tables_exist() -> None:
    """Create feedback tables if they do not exist yet."""
    ddl = """
    -- RLAIF feedback table (AI-generated scores)
    CREATE TABLE IF NOT EXISTS rl_feedback (
        id                  SERIAL PRIMARY KEY,
        run_id             VARCHAR(50) NOT NULL,
        user_query         TEXT NOT NULL,
        timestamp          TIMESTAMP DEFAULT NOW(),
        factual_accuracy   FLOAT,
        citation_completeness FLOAT,
        analysis_depth     FLOAT,
        structure_compliance FLOAT,
        language_quality   FLOAT,
        overall_score      FLOAT,
        strengths          JSONB DEFAULT '[]',
        weaknesses         JSONB DEFAULT '[]',
        specific_feedback  TEXT,
        agent_blamed       VARCHAR(50),
        report_excerpt     TEXT,
        ticker             VARCHAR(20)
    );
    CREATE INDEX IF NOT EXISTS idx_rl_feedback_run_id ON rl_feedback (run_id);
    CREATE INDEX IF NOT EXISTS idx_rl_feedback_timestamp ON rl_feedback (timestamp);
    CREATE INDEX IF NOT EXISTS idx_rl_feedback_agent_blamed ON rl_feedback (agent_blamed);

    -- User feedback table (explicit ratings)
    CREATE TABLE IF NOT EXISTS user_feedback (
        id                  SERIAL PRIMARY KEY,
        run_id             VARCHAR(50) NOT NULL,
        session_id         VARCHAR(50),
        timestamp          TIMESTAMP DEFAULT NOW(),
        helpful            BOOLEAN NOT NULL,
        comment            TEXT,
        issue_tags         JSONB DEFAULT '[]',
        report_version     VARCHAR(20)
    );
    CREATE INDEX IF NOT EXISTS idx_user_feedback_run_id ON user_feedback (run_id);
    CREATE INDEX IF NOT EXISTS idx_user_feedback_timestamp ON user_feedback (timestamp);

    -- Prompt versions table (tracking prompt changes)
    CREATE TABLE IF NOT EXISTS prompt_versions (
        id                  SERIAL PRIMARY KEY,
        agent_name         VARCHAR(50) NOT NULL,
        version            VARCHAR(20) NOT NULL,
        prompt_text        TEXT NOT NULL,
        deployed_at        TIMESTAMP DEFAULT NOW(),
        deployed_to        FLOAT DEFAULT 1.0,
        avg_score_before   FLOAT,
        avg_score_after    FLOAT,
        improvement_pct    FLOAT,
        weaknesses_addressed JSONB DEFAULT '[]'
    );
    CREATE INDEX IF NOT EXISTS idx_prompt_versions_agent ON prompt_versions (agent_name);
    CREATE INDEX IF NOT EXISTS idx_prompt_versions_version ON prompt_versions (version);
    """
    try:
        conn = _get_pg_conn()
        with conn:
            with conn.cursor() as cur:
                cur.execute(ddl)
        conn.close()
        logger.info("[feedback] Feedback tables created/verified successfully")
    except Exception as exc:
        logger.warning("[feedback] Could not create feedback tables: %s", exc)


def _call_deepseek_judge(
    report: str,
    user_query: str,
    agent_outputs_summary: str,
) -> Dict[str, Any]:
    """Call DeepSeek as a judge to score the report on multiple dimensions.
    
    Returns a dict with scores for each dimension and overall assessment.
    """
    import requests

    judge_system_prompt = """You are an expert equity research analyst and quality judge.
Your job is to evaluate investment research reports generated by an AI system.

You must score the report on these 5 dimensions (0-10 scale):

1. FACTUAL ACCURACY: Do all numbers match the original agent outputs? Are there any hallucinations?
2. CITATION COMPLETENESS: Does every claim with numbers have [N] citation? Are citations properly indexed?
3. ANALYSIS DEPTH: Does it explain WHY numbers matter? Or just dump data without analysis?
4. STRUCTURE COMPLIANCE: Are all 11 sections present in correct order per the research note format?
5. LANGUAGE QUALITY: Professional tone, no banned words (robust, solid, strong performance, etc.)

IMPORTANT: You must provide a JSON response with these exact keys:
- factual_accuracy (float 0-10)
- citation_completeness (float 0-10)
- analysis_depth (float 0-10)
- structure_compliance (float 0-10)
- language_quality (float 0-10)
- overall_score (float 0-10, weighted average)
- strengths (list of 3 strings)
- weaknesses (list of 3 strings)
- specific_feedback (string with detailed feedback)
- agent_blamed (string: "business_analyst" | "quant_fundamental" | "financial_modelling" | "web_search" | "summarizer" | "none")

The overall_score should weight: factual_accuracy 30%, citation_completeness 20%, 
analysis_depth 25%, structure_compliance 15%, language_quality 10%.

agent_blamed should identify which agent most likely caused any issues:
- If numbers are wrong → quant_fundamental or financial_modelling
- If missing citations → summarizer
- If analysis shallow → business_analyst
- If missing recent news → web_search
- If none of the above → "none"
"""

    judge_user_prompt = f"""Evaluate this research report:

USER QUERY: {user_query}

AGENT OUTPUTS SUMMARY (ground truth):
{agent_outputs_summary}

REPORT TO EVALUATE:
{report[:5000]}

Provide your evaluation as a JSON object."""

    try:
        headers = {
            "Authorization": f"Bearer {_DEEPSEEK_API_KEY}",
            "Content-Type": "application/json",
        }
        messages = [
            {"role": "system", "content": judge_system_prompt},
            {"role": "user", "content": judge_user_prompt},
        ]
        payload = {
            "model": _DEEPSEEK_MODEL,
            "messages": messages,
            "temperature": 0.1,
            "max_tokens": 2000,
        }
        resp = requests.post(
            f"{_DEEPSEEK_BASE_URL}/v1/chat/completions",
            json=payload,
            headers=headers,
            timeout=60,
        )
        resp.raise_for_status()
        content = resp.json().get("choices", [{}])[0].get("message", {}).get("content", "")
        
        # Extract JSON from response
        return _extract_json_from_response(content)
    except Exception as exc:
        logger.warning("[feedback] DeepSeek judge call failed: %s", exc)
        return {
            "factual_accuracy": 5.0,
            "citation_completeness": 5.0,
            "analysis_depth": 5.0,
            "structure_compliance": 5.0,
            "language_quality": 5.0,
            "overall_score": 5.0,
            "strengths": ["Unable to evaluate"],
            "weaknesses": ["Judge unavailable"],
            "specific_feedback": f"Error calling judge: {exc}",
            "agent_blamed": "none",
        }


def _extract_json_from_response(text: str) -> Dict[str, Any]:
    """Extract JSON from the judge's response."""
    import re
    
    # Try to find JSON block
    json_match = re.search(r'\{[^{}]*\}', text, re.DOTALL)
    if json_match:
        try:
            return json.loads(json_match.group())
        except json.JSONDecodeError:
            pass
    
    # Try to parse entire response as JSON
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    
    # Fallback to default scores
    logger.warning("[feedback] Could not parse judge response as JSON")
    return {
        "factual_accuracy": 5.0,
        "citation_completeness": 5.0,
        "analysis_depth": 5.0,
        "structure_compliance": 5.0,
        "language_quality": 5.0,
        "overall_score": 5.0,
        "strengths": ["Parse error"],
        "weaknesses": ["Could not evaluate"],
        "specific_feedback": "Could not parse judge response",
        "agent_blamed": "none",
    }


def score_report_with_rlaif(
    run_id: str,
    user_query: str,
    final_summary: str,
    agent_outputs: Dict[str, Any],
    ticker: Optional[str] = None,
) -> Dict[str, Any]:
    """Score a report using RLAIF and store the feedback.
    
    Args:
        run_id: Unique identifier for this run
        user_query: The original user query
        final_summary: The generated report
        agent_outputs: Dict containing all agent outputs for reference
        ticker: Optional ticker symbol
        
    Returns:
        Dict with RLAIF scores and feedback
    """
    ensure_feedback_tables_exist()
    
    # Build agent outputs summary for the judge
    outputs_parts = []
    if agent_outputs.get("business_analyst_output"):
        ba = agent_outputs["business_analyst_output"]
        outputs_parts.append(f"Business Analyst: confidence={ba.get('confidence')}, sentiment={ba.get('sentiment', {}).get('verdict', 'N/A')}")
    if agent_outputs.get("quant_fundamental_output"):
        qf = agent_outputs["quant_fundamental_output"]
        outputs_parts.append(f"Quant Fundamental: P/E={qf.get('value_factors', {}).get('pe_trailing')}, ROE={qf.get('quality_factors', {}).get('roe')}")
    if agent_outputs.get("financial_modelling_output"):
        fm = agent_outputs["financial_modelling_output"]
        dcf = fm.get("valuation", {}).get("dcf", {})
        outputs_parts.append(f"Financial Modelling: DCF base={dcf.get('intrinsic_value_base')}, WACC={dcf.get('wacc_used')}")
    if agent_outputs.get("web_search_output"):
        ws = agent_outputs["web_search_output"]
        outputs_parts.append(f"Web Search: sentiment={ws.get('sentiment_signal')}, news_count={len(ws.get('breaking_news', []))}")
    
    agent_outputs_summary = "\n".join(outputs_parts) if outputs_parts else "No agent outputs available"
    
    # Call DeepSeek judge
    scores = _call_deepseek_judge(final_summary, user_query, agent_outputs_summary)
    
    # Store in database
    try:
        conn = _get_pg_conn()
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO rl_feedback
                        (run_id, user_query, factual_accuracy, citation_completeness, 
                         analysis_depth, structure_compliance, language_quality, 
                         overall_score, strengths, weaknesses, specific_feedback, 
                         agent_blamed, report_excerpt, ticker)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    """,
                    (
                        run_id,
                        user_query,
                        scores.get("factual_accuracy"),
                        scores.get("citation_completeness"),
                        scores.get("analysis_depth"),
                        scores.get("structure_compliance"),
                        scores.get("language_quality"),
                        scores.get("overall_score"),
                        json.dumps(scores.get("strengths", [])),
                        json.dumps(scores.get("weaknesses", [])),
                        scores.get("specific_feedback"),
                        scores.get("agent_blamed"),
                        final_summary[:1000] if final_summary else None,
                        ticker,
                    ),
                )
        conn.close()
        logger.info("[feedback] RLAIF scores stored for run_id=%s, overall=%.2f", 
                    run_id, scores.get("overall_score", 0))
    except Exception as exc:
        logger.warning("[feedback] Failed to store RLAIF feedback: %s", exc)
    
    # Check if score is below threshold and log warning
    overall_score = scores.get("overall_score", 0)
    if overall_score < 7.0:
        logger.warning(
            "[feedback] Low RLAIF score (%.2f) for run_id=%s - agent_blamed=%s",
            overall_score, run_id, scores.get("agent_blamed")
        )
    
    return scores


def store_user_feedback(
    run_id: str,
    session_id: Optional[str],
    helpful: bool,
    comment: Optional[str] = None,
    issue_tags: Optional[List[str]] = None,
    report_version: Optional[str] = None,
) -> bool:
    """Store explicit user feedback from the UI.
    
    Args:
        run_id: Unique identifier for the run
        session_id: Optional session identifier
        helpful: True if user clicked thumbs up, False if thumbs down
        comment: Optional user comment
        issue_tags: List of issue types selected by user
        report_version: Which prompt version was used
        
    Returns:
        True if stored successfully
    """
    ensure_feedback_tables_exist()
    
    try:
        conn = _get_pg_conn()
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO user_feedback
                        (run_id, session_id, helpful, comment, issue_tags, report_version)
                    VALUES (%s, %s, %s, %s, %s, %s)
                    """,
                    (
                        run_id,
                        session_id,
                        helpful,
                        comment,
                        json.dumps(issue_tags or []),
                        report_version,
                    ),
                )
        conn.close()
        logger.info("[feedback] User feedback stored for run_id=%s, helpful=%s", run_id, helpful)
        return True
    except Exception as exc:
        logger.warning("[feedback] Failed to store user feedback: %s", exc)
        return False


def get_recent_rl_feedback(days: int = 7, min_score: float = 7.0) -> List[Dict[str, Any]]:
    """Get recent RLAIF feedback with low scores for analysis.
    
    Args:
        days: Number of days to look back
        min_score: Maximum score threshold (returns scores below this)
        
    Returns:
        List of low-scoring feedback records
    """
    ensure_feedback_tables_exist()
    
    try:
        conn = _get_pg_conn()
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute(
                """
                SELECT * FROM rl_feedback
                WHERE timestamp >= NOW() - INTERVAL '%s days'
                  AND overall_score < %s
                ORDER BY overall_score ASC, timestamp DESC
                """,
                (days, min_score),
            )
            rows = cur.fetchall()
        conn.close()
        return [dict(row) for row in rows]
    except Exception as exc:
        logger.warning("[feedback] Failed to get recent RLAIF feedback: %s", exc)
        return []


def get_user_feedback_summary(days: int = 7) -> Dict[str, Any]:
    """Get summary statistics for user feedback.
    
    Args:
        days: Number of days to look back
        
    Returns:
        Dict with summary statistics
    """
    ensure_feedback_tables_exist()
    
    try:
        conn = _get_pg_conn()
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            # Get total counts
            cur.execute(
                """
                SELECT 
                    COUNT(*) as total,
                    SUM(CASE WHEN helpful = true THEN 1 ELSE 0 END) as positive,
                    SUM(CASE WHEN helpful = false THEN 1 ELSE 0 END) as negative
                FROM user_feedback
                WHERE timestamp >= NOW() - INTERVAL '%s days'
                """,
                (days,),
            )
            counts = cur.fetchone()
            
            # Get issue tag distribution
            cur.execute(
                """
                SELECT issue_tags FROM user_feedback
                WHERE timestamp >= NOW() - INTERVAL '%s days'
                  AND issue_tags IS NOT NULL
                  AND jsonb_array_length(issue_tags) > 0
                """,
                (days,),
            )
            tag_counts: Dict[str, int] = {}
            for row in cur.fetchall():
                tags = row.get("issue_tags", [])
                if isinstance(tags, str):
                    tags = json.loads(tags)
                for tag in tags:
                    tag_counts[tag] = tag_counts.get(tag, 0) + 1
            
        conn.close()
        
        total = counts.get("total", 0) or 0
        positive = counts.get("positive", 0) or 0
        negative = counts.get("negative", 0) or 0
        
        return {
            "total_feedback": total,
            "positive_count": positive,
            "negative_count": negative,
            "positive_pct": (positive / total * 100) if total > 0 else 0,
            "negative_pct": (negative / total * 100) if total > 0 else 0,
            "issue_tag_counts": dict(sorted(tag_counts.items(), key=lambda x: x[1], reverse=True)),
        }
    except Exception as exc:
        logger.warning("[feedback] Failed to get user feedback summary: %s", exc)
        return {
            "total_feedback": 0,
            "positive_count": 0,
            "negative_count": 0,
            "positive_pct": 0,
            "negative_pct": 0,
            "issue_tag_counts": {},
        }


def get_agent_performance_summary(days: int = 7) -> Dict[str, Any]:
    """Get RLAIF performance summary by agent.
    
    Args:
        days: Number of days to look back
        
    Returns:
        Dict with per-agent performance metrics
    """
    ensure_feedback_tables_exist()
    
    try:
        conn = _get_pg_conn()
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute(
                """
                SELECT 
                    agent_blamed,
                    COUNT(*) as count,
                    AVG(overall_score) as avg_score,
                    AVG(factual_accuracy) as avg_factual,
                    AVG(citation_completeness) as avg_citation,
                    AVG(analysis_depth) as avg_analysis
                FROM rl_feedback
                WHERE timestamp >= NOW() - INTERVAL '%s days'
                  AND agent_blamed IS NOT NULL
                GROUP BY agent_blamed
                ORDER BY avg_score ASC
                """,
                (days,),
            )
            rows = cur.fetchall()
        conn.close()
        return {row["agent_blamed"]: dict(row) for row in rows}
    except Exception as exc:
        logger.warning("[feedback] Failed to get agent performance summary: %s", exc)
        return {}


def check_low_score_alert(days: int = 1, threshold: float = 7.0) -> List[Dict[str, Any]]:
    """Check for runs with low RLAIF scores that may need immediate attention.
    
    Args:
        days: Number of days to look back
        threshold: Score threshold to alert on
        
    Returns:
        List of low-scoring runs
    """
    ensure_feedback_tables_exist()
    
    try:
        conn = _get_pg_conn()
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute(
                """
                SELECT run_id, user_query, overall_score, agent_blamed, weaknesses, timestamp
                FROM rl_feedback
                WHERE timestamp >= NOW() - INTERVAL '%s days'
                  AND overall_score < %s
                ORDER BY timestamp DESC
                """,
                (days, threshold),
            )
            rows = cur.fetchall()
        conn.close()
        return [dict(row) for row in rows]
    except Exception as exc:
        logger.warning("[feedback] Failed to check low score alerts: %s", exc)
        return []


__all__ = [
    "ensure_feedback_tables_exist",
    "score_report_with_rlaif",
    "store_user_feedback",
    "get_recent_rl_feedback",
    "get_user_feedback_summary",
    "get_agent_performance_summary",
    "check_low_score_alert",
]
